[package]
name = "kwe-video-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
kwe-frame-protocol = { path = "../kwe-frame-protocol" }
kwe-input-protocol = { path = "../kwe-input-protocol" }
kwe-mpv = { path = "../kwe-mpv" }
libc.workspace = true
serde_json.workspace = true
