[package]
name = "kwe-scene-inspector"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
hex.workspace = true
kwe-core = { path = "../kwe-core" }
kwe-report-protocol = { path = "../kwe-report-protocol" }
libc.workspace = true
serde_json.workspace = true
sha2.workspace = true
